{
  books(orderBy: { createdAt: ASC }) {
    totalCount
    edges {
      node {
        title
        source
        cover {
          medium
          small
        }
        # subjects {
        #   title
        # }
        # persons {
        #   role
        #   person {
        #     name
        #   }
        # }
      }
    }
  }
}
