query BookQuery($id: Int!) {
  book(id: $id) {
    id
    title
    version
    HWR
    UWC
    source
    sourceId
    file
    cover {
      medium
      small
    }
    subjects {
      title
    }
    persons {
      role
      person {
        name
      }
    }
    level {
      A1 {
        count
        readability
      }
      A2 {
        count
        readability
      }
      B1 {
        count
        readability
      }
      B2 {
        count
        readability
      }
      C1 {
        count
        readability
      }
      C2 {
        count
        readability
      }
    }
  }
}
