fragment BookItem on Book {
  id
  title
  source
  version
  cover {
    medium
    small
  }
  level {
    A1 {
      count
      readability
    }
    A2 {
      count
      readability
    }
    B1 {
      count
      readability
    }
    B2 {
      count
      readability
    }
    C1 {
      count
      readability
    }
    C2 {
      count
      readability
    }
  }
}
query TopTenOfLevels{
  topTenOfLevels {
    A1 {
      ...BookItem
    }
    A2 {
      ...BookItem
    }
    B1 {
      ...BookItem
    }
    B2 {
      ...BookItem
    }
    C1 {
      ...BookItem
    }
    C2 {
      ...BookItem
    }
  }
}
