name: Build Android

env:
  VUE_APP_API_URL: https://backend.lamp-reader.com
  VUE_APP_HCAPTCHA_SITEKEY: 0aa34418-513d-4314-a1c0-ab5fbec5a56b
  VUE_APP_BASE_URL: http://localhost
  PUBLIC_PATH: /

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install app dependencies
        run: npm ci

      - name: Build App
        run: npm run ionic:sync

      - name: Build app bundle
        run: cd android && gradle bundle

      # - name: Extract Android signing key from env
      #   run: |
      #     echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
      #     base64 -d android/release.jks.base64 > android/release.decrypted.jks

      # - name: Sign dev build
      #   run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

      # - name: Upload release APK
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: app-release
      #     path: android/app/build/outputs/bundle/release/app-release-signed.apk
      #     retention-days: 30

      - name: Convert aab to apk
        id: convert_aab
        uses: mukeshsolanki/bundletool-action@v1.0.0
        with:
          aabFile: ./android/app/build/outputs/bundle/release/app-release.aab
          base64Keystore: ${{ secrets.RELEASE_KEYSTORE }}
          keystorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keystoreAlias: release
          keyPassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: ${{ steps.convert_aab.outputs.apkPath }}
