name: Build Android

env:
  VUE_APP_API_URL: https://zabanasly-backend.iran.liara.run
  VUE_APP_BASE_URL: http://localhost
  PUBLIC_PATH: /

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install app dependencies
        run: npm ci

      - name: Build App
        run: npm run ionic:sync

      - name: Build app bundle
        run: cd android && gradle bundle

      - name: Convert aab to apk
        id: convert_aab
        uses: mukeshsolanki/bundletool-action@v1.0.0
        with:
          aabFile: ./android/app/build/outputs/bundle/release/app-release.aab
          base64Keystore: ${{ secrets.RELEASE_KEYSTORE }}
          keystorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keystoreAlias: release
          keyPassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: ${{ steps.convert_aab.outputs.apkPath }}
